# Generated by Django 2.1.1 on 2018-11-15 18:55

import cevichecorp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoTieneCoevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestada', models.BooleanField()),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7), cevichecorp.models.validate_decimals])),
            ],
        ),
        migrations.CreateModel(
            name='Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('codigo', models.CharField(max_length=15)),
                ('seccion', models.IntegerField()),
                ('anho', models.IntegerField()),
                ('semestre', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('actual', models.BooleanField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Curso')),
                ('rut_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerteneceACurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Curso')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=200)),
                ('num_pregunta', models.IntegerField()),
                ('tipo_pregunta', models.CharField(max_length=20)),
                ('ponderacion', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('id_coev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Coevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestasAlumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.CharField(max_length=150)),
                ('id_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Preguntas')),
                ('rut_desde', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desde', to=settings.AUTH_USER_MODEL)),
                ('rut_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='para', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('codigo', 'seccion', 'anho', 'semestre')},
        ),
        migrations.AddField(
            model_name='coevaluacion',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Curso'),
        ),
        migrations.AddField(
            model_name='alumnotienecoevaluacion',
            name='id_coev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Coevaluacion'),
        ),
        migrations.AddField(
            model_name='alumnotienecoevaluacion',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.PerteneceACurso'),
        ),
        migrations.AlterUniqueTogether(
            name='respuestasalumnos',
            unique_together={('id_pregunta', 'rut_desde', 'rut_objetivo')},
        ),
        migrations.AlterUniqueTogether(
            name='preguntas',
            unique_together={('id_coev', 'num_pregunta', 'texto_pregunta')},
        ),
        migrations.AlterUniqueTogether(
            name='perteneceacurso',
            unique_together={('rut', 'id_curso')},
        ),
        migrations.AlterUniqueTogether(
            name='equipos',
            unique_together={('nombre', 'rut_alumno', 'id_curso')},
        ),
        migrations.AlterUniqueTogether(
            name='coevaluacion',
            unique_together={('nombre', 'id_curso')},
        ),
        migrations.AlterUniqueTogether(
            name='alumnotienecoevaluacion',
            unique_together={('id_curso', 'id_coev')},
        ),
    ]
