# Generated by Django 2.1.1 on 2018-11-15 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevichecorp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlumnoTieneCoevaluacion',
            new_name='AlumnoTieneCoev',
        ),
    ]
