# Generated by Django 2.1.3 on 2018-11-08 14:26

import cevichecorp.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cevichecorp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumnoTieneCoevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contestada', models.BooleanField()),
                ('nota', models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7), cevichecorp.models.validate_decimals])),
            ],
        ),
        migrations.CreateModel(
            name='Coevaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_termino', models.DateTimeField()),
                ('status', models.BooleanField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Curso')),
            ],
        ),
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('actual', models.BooleanField()),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Curso')),
                ('rut_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerteneceACurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Curso')),
                ('rut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pregunta', models.CharField(max_length=200)),
                ('num_pregunta', models.IntegerField()),
                ('ponderacion', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('id_coev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Coevaluacion')),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Curso')),
            ],
        ),
        migrations.AddField(
            model_name='alumnotienecoevaluacion',
            name='id_coev',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Coevaluacion'),
        ),
        migrations.AddField(
            model_name='alumnotienecoevaluacion',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cevichecorp.Curso'),
        ),
        migrations.AddField(
            model_name='alumnotienecoevaluacion',
            name='rut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
