# Generated by Django 2.1.1 on 2018-11-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevichecorp', '0002_auto_20181115_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AlumnoTieneCoev',
            new_name='AlumnoTieneCoevaluacion',
        ),
    ]
