# Generated by Django 2.1.3 on 2018-11-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevichecorp', '0002_auto_20181108_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='tipo_pregunta',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('codigo', 'seccion', 'anho', 'semestre')},
        ),
    ]
