# Generated by Django 2.1.3 on 2018-11-26 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevichecorp', '0006_auto_20181119_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perteneceacurso',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'Estudiante'), ('PROFESOR', 'Profesor'), ('PROFESOR AUXILIAR', 'Profesor auxiliar'), ('AYUDANTE', 'Ayudante')], max_length=20),
        ),
    ]
