# Generated by Django 2.1.1 on 2018-11-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevichecorp', '0008_auto_20181126_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perteneceacurso',
            name='rol',
            field=models.CharField(choices=[('ESTUDIANTE', 'alumno'), ('PROFESOR', 'profesor'), ('PROFESOR AUXILIAR', 'auxiliar'), ('AYUDANTE', 'ayudante')], max_length=20),
        ),
    ]
