# Generated by Django 2.1.3 on 2018-11-26 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cevichecorp', '0010_auto_20181126_0059'),
        ('cevichecorp', '0007_auto_20181126_1934'),
    ]

    operations = [
    ]
