# Generated by Django 2.1.3 on 2018-11-26 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cevichecorp', '0011_merge_20181126_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perteneceacurso',
            name='rol',
            field=models.CharField(choices=[('alumno', 'Estudiante'), ('profesor', 'Profesor'), ('auxiliar', 'Profesor auxiliar'), ('ayudante', 'Ayudante')], max_length=20),
        ),
    ]
